type CountryInfo = {
  country: string;
  agriculturalCrops: string[];
  deliveryOptions: string[];
};

const countries: CountryInfo[] = [
  {
    country: "germany",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "italy",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "france",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "spain",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "ukraine",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "turkey",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "bulgaria",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "croatia",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "belarus",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "germany",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "hungary",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "poland",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "portugal",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "romania",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "serbia",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
  {
    country: "slovakia",
    agriculturalCrops: [
      "Wheat",
      "Barley",
      "Corn",
      "Sorghum",
      "Rye",
      "Oats",
      "Sunflower",
      "Soybean",
      "Rapeseed",
      "Linseed",
    ],
    deliveryOptions: ["CIF", "FAC", "FCA", "CFR"],
  },
];

export default countries;
