import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import classNames from "classnames";
import HeaderComponent from "@/components/HeaderComponent";
import FooterComponent from "@/components/FooterComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = localFont({
  src: [
    {
      path: "./../style/fonts/manrope-400.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../style/fonts/manrope-500.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../style/fonts/manrope-600.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../style/fonts/manrope-700.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={classNames(manrope.className)}>
      <body>
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
