import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import classNames from "classnames";
import HeaderComponent from "@/components/HeaderComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = localFont({
  src: [
    {
      path: "./../style/fonts/Manrope-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../style/fonts/Manrope-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../style/fonts/Manrope-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../style/fonts/Manrope-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={classNames(manrope.className)}>
      {" "}
      <HeaderComponent />
      <body>{children}</body>
    </html>
  );
}
